"""Copy the sealed V0 runner; change only prior residual learning/additional bias."""
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]; OUT = ROOT / "work/grid21"
text = (ROOT / "work/grid20/run.py").read_text(encoding="utf-8")
text = text.replace('str(ROOT / "work/grid20")]', 'str(ROOT / "work/grid20"), str(ROOT / "work/grid21")]')
text = text.replace('from rules import shortlist_rules','from rules import shortlist_rules\nfrom prior import public_prior, ResidualScorer')
text = text.replace('ROOT / "outputs/grid20"','ROOT / "outputs/grid21"')
text = text.replace('reps, aliases = canonical_groups(features, ids)', 'reps, aliases = canonical_groups(features, ids)\n            t_prior = time.perf_counter()\n            prior, prior_order = public_prior(before,env,ctl,ids,aliases)\n            prior_s = time.perf_counter()-t_prior\n            feature_s += prior_s')
text = text.replace('target=target, mask=mask, representatives=np.asarray(reps)', 'target=target, mask=mask, prior=prior, representatives=np.asarray(reps)')
text = text.replace('"feature_build_s": feature_s})','"feature_build_s": feature_s, "prior_s": prior_s, "prior_hash": digest(prior)})')
text = text.replace('"target": torch.as_tensor(target), "mask": torch.as_tensor(mask),','"target": torch.as_tensor(target), "mask": torch.as_tensor(mask), "prior": torch.as_tensor(prior),')
text = text.replace('return CandidateScorer(kind,', 'return ResidualScorer(kind,')
text = text.replace('logits = model(**batch(selected))','residual = model(**batch(selected))\n            prior_logs = torch.stack([r["prior"] for r in selected])\n            logits = residual+prior_logs')
text = text.replace('loss = -(target*logs).sum(1).mean(); assert torch.isfinite(loss)', 'prior_normalized = torch.nn.functional.log_softmax(prior_logs.masked_fill(~masks,-1e9),dim=1)\n            regularizer = (logs.exp()*(logs-prior_normalized)).sum(1).mean()\n            loss = -(target*logs).sum(1).mean()+D["prior_KL_weight"]*regularizer; assert torch.isfinite(loss)')
text = text.replace('values = model(**row["tensor"])[0].numpy().copy()', 'values = (model(**row["tensor"])[0]+row["prior"]).numpy().copy()')
text = text.replace('for order in result.values(): assert', 'result["PRIOR_ONLY"] = sort(row["prior"].numpy()); timings["PRIOR_ONLY"] = 0.\n    assert result["PRIOR_ONLY"] == result["OLDNN"]\n    for order in result.values(): assert')
text = text.replace('for kind in ["gnn", "mlp"]:', 'for kind in ["gnn", "mlp", "bias"]:')
text = text.replace('training_cross_entropy', 'training_objective')
(OUT / "run.py").write_text(text,encoding="utf-8")
assert 'prior_normalized' in text and text.count('public_prior(before,env,ctl,ids,aliases)') == 1
print("Generated GRID21 runner from sealed V0, original unchanged.")

audit = (ROOT / "work/grid20/audit.py").read_text(encoding="utf-8")
audit = audit.replace('str(ROOT / "work/grid20")]', 'str(ROOT / "work/grid20"),str(ROOT / "work/grid21")]')
audit = audit.replace('from components import CandidateScorer,', 'from prior import ResidualScorer, public_prior\nfrom components import CandidateScorer,')
audit = audit.replace('ROOT / "outputs/grid20"','ROOT / "outputs/grid21"')
audit = audit.replace('first = {}; representatives = []','first = {}; representatives = []; aliases = {}')
audit = audit.replace('rep = first[key]\n', 'rep = first[key]; aliases[i] = rep\n')
audit = audit.replace('assert representatives == saved["representatives"].tolist()', 'assert representatives == saved["representatives"].tolist()\n            prior,_ = public_prior(obs,env,ctl,eligible,aliases)\n            assert np.array_equal(prior,saved["prior"]) and digest(prior) == meta["prior_hash"]')
audit = audit.replace('"target":saved["target"],"mask":saved["mask"]}', '"target":saved["target"],"mask":saved["mask"],"prior":saved["prior"]}')
audit = audit.replace('for kind in ["gnn","mlp"]', 'for kind in ["gnn","mlp","bias"]')
audit = audit.replace('model = CandidateScorer(', 'model = ResidualScorer(')
audit = audit.replace('logits = model(**tensors(r["features"]))[0]', 'correction = model(**tensors(r["features"]))[0]\n            assert correction.abs().max()<=2.+1e-6\n            logits = correction+torch.as_tensor(r["prior"])')
audit = audit.replace('values = model(**tensors(r["features"]))[0].numpy()', 'values = (model(**tensors(r["features"]))[0]+torch.as_tensor(r["prior"])).numpy()')
audit = audit.replace('assert stored["orders"]["PREFIX"] == reps', 'assert stored["orders"]["PREFIX"] == reps\n        original = json.loads((ROOT / "outputs/grid20/orders" / f"{identifier}.json").read_text())\n        assert stored["orders"]["OLDNN"] == original["orders"]["OLDNN"] == stored["orders"]["PRIOR_ONLY"]')
(OUT / "audit.py").write_text(audit,encoding="utf-8")
