$ErrorActionPreference='Stop'
$base=Join-Path $PSScriptRoot '..'; $out=Join-Path $base 'outputs'; $runs=Join-Path $base 'runs'; $graphDir=Join-Path $base 'graphs'
$rows=@(Import-Csv (Join-Path $out 'run_results.csv'))
foreach($r in $rows){if($r.elapsed_source -eq 'recovered_solver_reported_time'){$r.elapsed_source='wall_not_captured_solver_time_from_log'}}
$rows|Export-Csv -NoTypeInformation -Encoding utf8 -LiteralPath (Join-Path $out 'run_results.csv')
$cutBad=@($rows|Where-Object cut_match -ne 'True').Count; $balanceBad=@($rows|Where-Object balance_feasible -ne 'True').Count; $exitBad=@($rows|Where-Object exit_code -ne '0').Count
$probe=Get-Content -Raw (Join-Path $out 'k_feature_probe.json')|ConvertFrom-Json
$default=@(Import-Csv (Join-Path $out 'default_model_invocation.csv'))
$audit=[ordered]@{main_matrix_runs=$rows.Count;all_exit_zero=($exitBad -eq 0);independent_cut_mismatches=$cutBad;balance_failures=$balanceBad;default_model_invocation_checks=$default;feature_probe=$probe;time_caveat='External process wall time was not captured for one completed matrix run; its solver-reported partition time is retained. Learned runs had opt-in feature-export overhead, so timings are not a fair speed comparison.';outputs=@('run_results.csv','k_conditioning.csv','default_model_invocation.csv','k_feature_probe.json','build_manifest.json','feature_dictionary.csv')}
$audit|ConvertTo-Json -Depth 8|Set-Content -LiteralPath (Join-Path $out 'audit.json') -Encoding utf8
$names=@('comm_1_equal','N1<degree_quantile>','modularity_1','modularity_2','modularity_0','N0<degree>','N1<min_contracted_degree>','N0<min_contracted_degree>','N1<degree>','N0<q3_degree>','N1<sd_degree>','N1<min_contracted_degree_size>','N0<degree_quantile>','strawman_similarity','N0<med_degree>','N1<med_degree>','N1<q1_degree>','N0<sd_degree>','N1<q3_degree>','N0<skew_degree>','N1<skew_degree>','N0<entropy_degree>','N0<avg_degree>','N1<avg_degree>','N1<min_degree>','N0<q1_degree>','N0<min_contracted_degree_size>','N1<entropy_degree>','N1<max_degree>','N0<max_degree>','comm_2_equal','N0<d1_nodes>')
$dict=[System.Collections.Generic.List[object]]::new();for($i=0;$i -lt $names.Count;$i++){$name=$names[$i];$role='endpoint feature';if($name -match '^N0<(.+)>$'){$role='canonical endpoint 0: '+$Matches[1]}elseif($name -match '^N1<(.+)>$'){$role='canonical endpoint 1: '+$Matches[1]}elseif($name -match '^modularity_'){$role='global feature'}elseif($name -match 'equal$' -or $name -eq 'strawman_similarity'){$role='edge feature'};$dict.Add([pscustomobject]@{index=$i;model_feature=$name;role=$role;explicit_k_input=$false;notes='N0/N1 use source-code canonical endpoint ordering (higher degree first, then higher node ID); community flags can use preprocessing community_stack.'})};$dict|Export-Csv -NoTypeInformation -Encoding utf8 -LiteralPath (Join-Path $out 'feature_dictionary.csv')
# Compact exact 16-run table for the report.
$lines=[System.Collections.Generic.List[string]]::new()
$lines.Add('# GP00 报告：工程与假设资格检查')
$lines.Add('')
$lines.Add('**结论：工程资格检查通过；默认配置下 k=32 不触发学习粗化。** 16个预定矩阵运行均成功，独立 cut 重算与程序结果全部一致，平衡约束全部满足。模型输入敏感性仅在单个补充诊断配置下直接比较：ER seed 0 的 k=4 与 k=32 输入向量及分数完全相同。小图胜负不用于研究价值判断。')
$lines.Add('')
$lines.Add('## 版本、输入与命令')
$lines.Add('')
$lines.Add('- Mt-KaHyPar 源码固定在 `6d12d9cf210390624f3757e9b5399469d2d2ae68`（2026-04-02；README reproduction instructions）。运行时 `sea2026` 名称没有可直接取用的 Git ref；该提交是复现代码快照。')
$lines.Add('- `grid32x32_4n`：1024节点、1984条无向边的四邻接网格。`er1024_p001_seed20260930`：G(1024, 0.01)，遍历无序节点对 `(u,v)` 并用 PowerShell 7.6.5 / .NET `System.Random(20260930)` 抽样，得到5236条无向边。输入哈希与生成规则见 `../graphs/input_manifest.json`。')
$lines.Add('- 主矩阵固定 `k=4,32`、ε=0.03、线程数1、求解 seed 0/1、目标 cut。学习臂使用默认 SEA 2026 配置；匹配非学习臂额外设置 `--c-guiding-by-integrated-model=false --c-rating-degree-similarity-policy=always_accept`。完整逐次命令见 `../runs/run_manifest.json`。')
$lines.Add('- README 示例写 `--preset=default`，但该提交的 CLI 将 `--preset` 解释为自定义 INI 路径；实际合法的默认预设参数是 `--preset-type=default`，本轮按源码接口运行。')
$lines.Add('')
$lines.Add('## 16次主矩阵结果')
$lines.Add('')
$lines.Add('| 图 | k | seed | 配置 | 独立 cut | 程序 cut | 块大小范围 | 平衡 | 求解器计时(s) | 外部墙钟(s) |')
$lines.Add('|---|---:|---:|---|---:|---:|---|---|---:|---:|')
foreach($r in $rows){$wall='';if($r.external_wall_seconds){$wall=[Math]::Round([double]$r.external_wall_seconds,6).ToString([Globalization.CultureInfo]::InvariantCulture)}else{$wall='未记录'};$min=[int]$r.min_block;$max=[int]$r.max_block;$solver=[Math]::Round([double]$r.solver_partitioning_seconds,6).ToString([Globalization.CultureInfo]::InvariantCulture);$method=if($r.method -eq 'learned'){'学习'}else{'非学习'};$graph=if($r.graph -eq 'grid32x32_4n'){'32×32网格'}else{'ER'};$lines.Add("| $graph | $($r.k) | $($r.seed) | $method | $($r.cut_independent) | $($r.cut_solver) | $min–$max | $($r.balance_feasible) | $solver | $wall |")}
$lines.Add('')
$lines.Add('所有16次退出码为0；独立 cut 与求解器 cut 全部相符；16/16平衡。最大块容量按 `floor((1+0.03)·1024/k)` 复核：k=4为263，k=32为32。结果只是两张小图的工程检查，不作方法质量推断。')
$lines.Add('')
$lines.Add('运行时间限制：矩阵中8个学习臂启用了只读特征/分数导出，导出开销计入了内部计时，因此学习与非学习计时不可直接比较。另有一个完成的主矩阵运行未保存外部进程墙钟时间；其内部求解器时间0.124623秒从日志保留。')
$lines.Add('')
$lines.Add('## k 是否进入模型输入')
$lines.Add('')
$lines.Add('默认预设将收缩目标设为 `t·k`，t=160。1024节点图上，k=4的收缩上限是640，触发一次初始学习评分；k=32上限是5120，大于图规模，粗化无需执行，因此默认 k=32 路径没有模型预测。这个观察说明两张测试图的默认高 k 路径跳过学习粗化，不能解读为模型在默认配置下对 k=32 的评分与 k=4 相同。')
$lines.Add('')
$lines.Add('为直接核验模型被调用时的输入，另做ER图 seed 0 的两次特征诊断：k=4与k=32均使用 `--c-t=20`，其余参数相同。该参数仅为触发两侧模型调用；诊断不计入16次默认配置成绩。两侧各导出10472条有向弧，逐边对齐无误：32维原始向量335104/335104项相同，归一化向量335104/335104项相同，预测10472/10472项相同，最大差均为0。每个无向边的两个方向均存在，反向弧向量与预测一致。详细值在两个 `featurediag_er1024_s0_k*_ct20/model_features.csv`，差异汇总见 `k_feature_probe.json`。')
$lines.Add('')
$lines.Add('因此，在这个ER图/seed及共同 `c-t=20` 配置下，作者模型当前32维显式特征与预测不随 k 改变。代码会读取 community stack，因此这不是对所有图、预处理或粗化层的普遍结论。特征字段顺序与角色见 `feature_dictionary.csv`。')
$lines.Add('')
$lines.Add('## 评分替换入口与跨层规则')
$lines.Add('')
$lines.Add('- 内部入口是 `computeEdgeMetadataFromModel()`，会从固定模型生成每条静态图有向邻接弧的 `EdgeMetadata`。源代码按端点度数、再按节点ID规范端点方向以计算特征；每条无向 METIS 边因此有两个方向的edge ID/预测。特征导出保持原始 source/target，并保留 `edge_id` 供核对。')
$lines.Add('- 评分保存在 edge metadata，不改原始边权；后续 Heavy-Edge rating 仍由原图权重/度数计算。`StaticGraph::contract()` 用邻接槽位索引对应 metadata；并行边收缩去重时把 metadata 相加。默认累积类型是 linear，合并评分与合并rating做比值后由指导阈值决定接受和权重缩放。最终 cut 优化目标与后续细化仍使用原边权。')
$lines.Add('- 未找到外部评分文件的命令行接口；目前需要在源码模型入口替换或加入注入路径。此次没有实现替代评分器。')
$lines.Add('')
$lines.Add('## 构建偏差与适用边界')
$lines.Add('')
$lines.Add('Windows MinGW 下为完成本地编译做了仅限构建/审计的修改：预取依赖按上游 pin 预置，以绕过 CMake 4.1 + MinGW Makefiles 的相对 FetchContent 子构建路径问题；oneTBB 的 GNU 汇编器探测改为 Windows 下关闭可选 WAITPKG 汇编；`mlp.c` 在 Windows 分支使用 `_aligned_malloc/_aligned_free`；让源码声明的 `KAHYPAR_DISABLE_GROWT` 选项生效，并关闭该可选 Growt 依赖；CMake 生成的对象响应文件改为绝对对象路径以供 MinGW `ar` 读取；另外增加默认关闭的特征导出环境钩子。主矩阵的算法选项保持作者默认/匹配基线设置。')
$lines.Add('')
$lines.Add('本轮不下载标签数据、不训练、不生成教师标签。上述结果只证明当前机器能在固定小图上运行及审计评分路径；k 条件化收益、强求解器中的质量差异以及论文贡献均尚未建立。')
$lines.Add('')
$lines.Add('## 产物')
$lines.Add('')
$lines.Add('- `run_results.csv`：逐运行独立重算、cut 对账、平衡检查与计时。')
$lines.Add('- `../runs/run_manifest.json`：16条完整命令、配置、输入哈希和运行状态。')
$lines.Add('- `default_model_invocation.csv`：默认 k=4/32 是否实际触发预测。')
$lines.Add('- `k_feature_probe.json`：受控 k 差异及有向弧一致性诊断。')
$lines.Add('- `feature_dictionary.csv`：32维模型输入顺序和语义。')
$lines.Add('- `build_manifest.json`：提交、依赖提交、编译器、构建配置与二进制哈希。')
$lines.Add('- `../runs/<run>/stdout.log` 和 `input.graph.part*`：原始日志与完整划分。模型臂的 `model_features.csv` 保存实际预测分数及原始/归一化向量。')
[IO.File]::WriteAllLines((Join-Path $out 'GP00_report.md'),$lines,[Text.UTF8Encoding]::new($false))
Write-Output "main_runs=$($rows.Count) exits_ok=$($exitBad -eq 0) cut_mismatches=$cutBad balance_failures=$balanceBad"
Write-Output (Join-Path $out 'GP00_report.md')
