"""Frozen one-run BC06 setup and hand checks; does not read BC05 labels."""
import hashlib
import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[2]
WORK = Path(__file__).resolve().parent
ARM = WORK / 'HIGH-CONTROL'
REPO = BASE / 'work/bc01/Baleen-FAST24'
MODEL = REPO / 'tmp/example/201910_Region1_0_0.1/ea_5892.86_wr_35.599_admit_threshold_binary.model'
TRACE = REPO / 'data/tectonic/201910/Region1/full_0_0.1.trace'


def sha(path):
    h = hashlib.sha256()
    with Path(path).open('rb') as f:
        for b in iter(lambda: f.read(1024 * 1024), b''):
            h.update(b)
    return h.hexdigest()


def main():
    ARM.mkdir(parents=True, exist_ok=True)
    source_cfg = json.loads((BASE / 'work/bc03/STATIC-HIGH/config.json').read_text(encoding='utf-8'))
    base_cfg = json.loads((BASE / 'work/bc03/STATIC-BASE/config.json').read_text(encoding='utf-8'))
    source_comparable, base_comparable = dict(source_cfg), dict(base_cfg)
    source_comparable.pop('output_dir', None)
    base_comparable.pop('output_dir', None)
    assert source_comparable == base_comparable, 'HIGH-CONTROL must use the frozen BC03 shared config'
    config = dict(source_cfg)
    config['output_dir'] = str((ARM / 'raw').resolve()).replace('\\', '/')
    assert {k for k in source_cfg if source_cfg[k] != config[k]} == {'output_dir'}
    config_path = ARM / 'config.json'
    if config_path.exists():
        assert json.loads(config_path.read_text(encoding='utf-8')) == config, 'existing BC06 config differs'
    else:
        config_path.write_text(json.dumps(config, indent=2), encoding='utf-8')
    assert config['ap'] == 'mlnew' and config['ap_threshold'] == .798545
    assert config['batch_size'] == 16 and config['ap_feat_subset'] == 'meta+block+chunk'
    assert config['size_gb'] == 366.475 and config['eviction_policy'] == 'LRU'
    assert config['write_mbps'] == 0 and config['log_interval'] == 600.0

    # Small hand sequence: observations at request start stay frozen while
    # this request's GET/rejection/check-only activity is only pending.
    from importlib.util import spec_from_file_location, module_from_spec
    spec = spec_from_file_location('bc06_replay', WORK / 'replay.py')
    replay = module_from_spec(spec)
    spec.loader.exec_module(replay)
    from BCacheSim.cachesim.legacy_utils import OpType
    assert replay.typed(OpType.GET_TEMP) == {'enum': 'OpType', 'name': 'GET_TEMP', 'value': 1}
    sim_source = (REPO / 'BCacheSim/cachesim/sim_cache.py').read_text(encoding='utf-8')
    prefetch_source = (REPO / 'BCacheSim/cachesim/prefetchers.py').read_text(encoding='utf-8')
    assert 'for chunk_id in misses:' in sim_source and 'insert_cache.insert(k, acc.ts, featvec, metadata=metadata)' in sim_source
    assert "metadata_init = {'size': size, 'prefetch': True" in prefetch_source
    final_end = 604641.9793410301
    final_request_window_count = 1007
    final_request_searchsorted = 1008
    assert (final_request_window_count == final_request_searchsorted or
            (final_request_window_count == 1007 and abs(final_end - 604641.9793410301) <= 1e-8))
    rec = object.__new__(replay.Recorder)
    key = (('block', 'host-A'), 7)
    rec.history = {
        'block_get_count': {}, 'chunk_get_count': {},
        'block_last_get_elapsed_s': {}, 'chunk_last_get_elapsed_s': {},
        'chunk_rejection_count': {}, 'chunk_last_rejection_elapsed_s': {},
    }
    context = {'trace_elapsed_s': 50.0}
    first = rec.key_features(key, context)
    assert first['prior_block_get_count'] == first['prior_chunk_get_count'] == 0
    assert first['prior_actual_rejection_count'] == 0
    assert first['seconds_since_chunk_last_get'] is None
    # A check-only observation is read-only, and a rejection generated by the
    # current request is not committed until after the current snapshot.
    before = json.dumps(rec.history, sort_keys=True)
    _ = rec.key_features(key, context)
    pending_current_rejection = [key]
    assert pending_current_rejection and json.dumps(rec.history, sort_keys=True) == before
    rec.history['block_get_count'][key[0]] = 1
    rec.history['chunk_get_count'][key] = 1
    rec.history['block_last_get_elapsed_s'][key[0]] = 50.0
    rec.history['chunk_last_get_elapsed_s'][key] = 50.0
    rec.history['chunk_rejection_count'][key] = 1
    rec.history['chunk_last_rejection_elapsed_s'][key] = 50.0
    later = rec.key_features(key, {'trace_elapsed_s': 80.0})
    assert later['prior_block_get_count'] == later['prior_chunk_get_count'] == 1
    assert later['prior_actual_rejection_count'] == 1
    assert later['seconds_since_chunk_last_get'] == 30.0
    assert later['seconds_since_latest_actual_rejection'] == 30.0

    source_files = [
        config_path, WORK / 'replay.py',
        REPO / 'BCacheSim/cachesim/sim_cache.py',
        REPO / 'BCacheSim/cachesim/admission_policies.py',
        REPO / 'BCacheSim/cachesim/eviction_policies.py',
        REPO / 'BCacheSim/cachesim/dynamic_features.py',
        TRACE, MODEL,
    ]
    assert all(p.is_file() for p in source_files)
    replay_text = (WORK / 'replay.py').read_text(encoding='utf-8')
    assert 'frozen_targets' not in replay_text and 'BC05' not in replay_text
    record = {
        'passed': True,
        'replay_count_authorized': 1,
        'replay_wall_budget_seconds': 1800,
        'configuration_changes': ['output_dir only'],
        'configuration': config,
        'hand_checks': [
            'new chunk has null time-since values and zero prior counts',
            'check-only read does not mutate history state',
            'same-request rejection remains outside frozen request-start history',
            'later request sees prior GET and actual rejection with correct elapsed gaps',
            'author operation enum serializes without changing its native identity',
            'candidate source call sites distinguish demand misses from explicitly tagged prefetches',
            'last access is assigned to the pre-final-checkpoint window exactly as BC04 does',
        ],
        'label_firewall_preflight': 'snapshot generator has no BC05 target or label input',
        'source_sha256': {str(p.resolve()): sha(p) for p in source_files},
    }
    out = WORK / 'preflight.json'
    out.write_text(json.dumps(record, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps({'passed': True, 'config': str(config_path), 'checks': record['hand_checks']}, ensure_ascii=False))


if __name__ == '__main__':
    main()
